ssimport streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import IsolationForest

# --- CONFIGURATION ---
st.set_page_config(page_title="Windows AI Security Analyzer Pro", layout="wide")

st.title("🛡️ Windows AI Security Anomaly Detection")
st.markdown("""
This dashboard processes the **Formal Multi-File Report** generated by your new audit script.
1. Run `windows_system_audit.py` on your target machine.
2. Upload the generated CSV files from the `audit_output` folder.
""")

# --- UPLOAD SECTION ---
st.header("📤 Step 1: Upload Audit CSVs")
uploaded_files = st.file_uploader(
    "Drag and drop multiple CSV files here from your report folder", 
    type=["csv"], 
    accept_multiple_files=True
)

if uploaded_files:
    # Map filenames to DataFrames
    file_map = {file.name.upper(): pd.read_csv(file) for file in uploaded_files}
    
    # --- AI ANALYSIS ---
    st.header("📊 AI Anomaly Analysis")
    all_numeric = []
    for df in file_map.values():
        all_numeric.append(df.select_dtypes(include=['number']))
    
    combined_numeric = pd.concat(all_numeric, axis=1).fillna(0)

    if not combined_numeric.empty:
        model = IsolationForest(n_estimators=100, contamination=0.05, random_state=42)
        preds = model.fit_predict(combined_numeric)
        
        anomalies = (preds == -1).sum()
        risk_score = round((anomalies / len(preds)) * 100, 2)

        c1, c2, c3 = st.columns(3)
        c1.metric("Data Points Analyzed", len(preds))
        c2.metric("Detected Anomalies", anomalies)
        c3.metric("Risk Score", f"{risk_score}%")

    # --- CATEGORIZED TABS ---
    st.header("🔍 System Audit Details")
    tab1, tab2, tab3, tab4 = st.tabs(["🌐 Network", "⚙️ Processes", "🛡️ Security & Users", "📂 All Data"])

    def clean(df):
        return df.drop(columns=["Audit_Reference_Timestamp", "Asset_Hostname", "Section_Title"], errors='ignore')

    with tab1:
        for name, df in file_map.items():
            if any(k in name for k in ["PORT", "CONNECTION", "IP"]):
                st.subheader(f"Data Source: {name}")
                st.dataframe(clean(df), use_container_width=True)

    with tab2:
        for name, df in file_map.items():
            if any(k in name for k in ["PROCESS", "STARTUP", "PROGRAM"]):
                st.subheader(f"Data Source: {name}")
                st.dataframe(clean(df), use_container_width=True)

    with tab3:
        for name, df in file_map.items():
            if any(k in name for k in ["USER", "ADMIN", "POLICY", "STATUS", "FIREWALL"]):
                st.subheader(f"Data Source: {name}")
                st.dataframe(clean(df), use_container_width=True)

    with tab4:
        for name, df in file_map.items():
            with st.expander(f"Raw File: {name}"):
                st.dataframe(df)
else:
    st.info("Waiting for CSV files...")
